export const JWT_PUBLIC_KEY =
  process.env.JWT_PUBLIC_KEY ||
  `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuyLriMkbDicFOtIMb1tA
xYzDtd/1WUNCXy6v6ko7CB71p5DnKYvEn4ptp0HxuOKWJoADQb6H6T5HBhKaPwZe
weBCTXmgRMpI8XM1yNtei9bDguHJuQ0Ss9Yu1zuBY9zqaK3zN3YDb2OUngo0XeRH
rbMqIC2CMuavtUH90kWWDVdVAXJMRPlc7JkUQ815p+OsTmlYCIthcSfc8hFQQ6vV
txISr/KTD2mubR/0GSSczUuB9cgsLeTrnY8dFKCWcYvPKmHt+SiZcpBqevqWHoGJ
1wkpVvWm7nDmypwmfWCYnyUOF+XQDxk3KfV3DCcXrWCV1CfQRh3GhAgnjaUlQNKk
eQIDAQAB
-----END PUBLIC KEY-----
`;
